### ISSUE TITLE
Support Prometheus Collector interface

### ISSUE THREAD

**Issue by bharathi-tenneti** [kubernetes/kube-state-metrics#1154]
/kind feature

kube-state-metrics does not support exposing its metrics via the standard prometheus client_golang interfaces. But that sort of interoperability would make it much easier to integrate kube-state-metrics with existing prometheus APIs.

There is draft work done by @joelanford [here](https://github.com/kubernetes/kube-state-metrics/compare/release-1.9...joelanford:collector-interface?expand=1#diff-fcdf11f2dec55adb751454678688300c). Please let us know thoughts on this, happy to submit PR.

/cc @joelanford

**Comment by brancz** [comment]
The reason why we don't is because serialization of standard client_golang is _much_ slower than the highly optimized version we have. Normal client_golang is perfectly sufficient for practically everything, except kube-state-metrics, where we tend to have extremely large scrapes (we often see >50Mb). The optimizations we've done are also not usable as a general purpose client, they only really fit the kube-state-metrics use case. We essentially pre-compute the text output based on the informers and when Prometheus comes around to scrape, we just have to copy the byte buffers onto the HTTP response. If we piped this through the `prometheus.Collector` interface then we would be loosing all these performance improvements.

**Comment by joelanford** [comment]
@brancz Thanks for the explanation! Makes sense. Our use case is to provide a library to make it easy for operator developers to publish kube-state-metrics-style metrics for their owned CRDs.

Do you foresee any scaling issues our users would run into if they instrumented metrics for _just_ their owned CRDs using prometheus client_golang APIs?

**Comment by brancz** [comment]
It's unpredictable, in OpenShift we also opted to use kube-state-metrics as a library for openshift-state-metrics, and there image-streams (also "just" a single resource) were also in need for these performance improvements. Some will always need this, so I wouldn't say it's safe to generalize.

I assume you're investigating this so that you only have a single endpoint. Something that we could try is create a handler, that first reads all metrics from a registry and then all metrics from this library.

**Comment by joelanford** [comment]
> I assume you're investigating this so that you only have a single endpoint. Something that we could try is create a handler, that first reads all metrics from a registry and then all metrics from this library.

In operator-sdk we have a library that has some helpers that basically take a `rest.Config`, a list of namespaces, and a list of GVKs and generate some simple out-of-box metrics for instances of GVKs found in those namespaces. Right now that library runs a totally separate server that handles these built-in metrics.

We're looking for ways to generalize this to make it easier to integrate into controller-runtime:
1. controller-runtime exposes a client_golang `Registry` and some simple knobs to enable running a server for that registry out-of-the box. The UX is basically "register some metrics with `metrics.Registry` and set a listen address". Controller-runtime manages the entire listener and http server execution under the hood. Some metrics come for free built-in and operator developers can define and register their own. We were thinking about whether it was possible to hook into that.
2. Also, controller-runtime is already running a bunch of list-watchers on primary resources so that it can call an operator's `Reconcile` method. So we're looking for ways to hook into that existing event stream instead of creating and running parallel list-watchers. We've thought of:
  a. Defining some optional interfaces for client_golang metrics types to implement that would allow those metrics to define callbacks when events happen, and then running those callbacks as part of a controller-runtime watch predicate.
  b. Defining a generic `Reconciler` implementation that does something similar to option 1, but in a `Reconcile` method instead of a Predicate.
  c. Documenting ways users can update metrics directly in their existing Reconciler implementations, and potentially writing some helpers to make that easier.

We're thinking that it would be nice to come up with something similar to 1) where controller-runtime users have a simple on/off switch to get some default built-in kube-state-metrics style metrics and some additional knobs to have a way of injecting their own metrics that are specific to their CRD API.

**Comment by brancz** [comment]
I think we're saying the same thing, just different approaches to achieving it.
