### ISSUE TITLE
Show last pod state and termination reason

### ISSUE THREAD

**Issue by Delorien84** [kubernetes/kube-state-metrics#1227]
/kind feature

**What happened**:
Sometimes pod is killed by various reason, but the reason is not visible in Lens. I need to execute `kubectl` command to see last state and reason why the pod was killed

**What you expected to happen**:
I would like to see in pod detail `Last State` and `Reason` similary to see when executing `kubectl describe pod <pod_name>`.

```
State:          Waiting
  Reason:       CrashLoopBackOff
Last State:     Terminated
  Reason:       OOMKilled
  Exit Code:    137
  Started:      Tue, 15 Sep 2020 08:45:37 +0200
  Finished:     Tue, 15 Sep 2020 08:45:38 +0200
```

**How to reproduce it (as minimally and precisely as possible)**:
Just create pod that is killed due to out of memory

**Comment by dgrisonnet** [comment]
Hi @Delorien84, you can already have this information via the `kube_pod_container_status_terminated_reason` and `kube_pod_container_status_last_terminated_reason` metrics.
In order to bound the cardinality of such metrics, there is a limited list of reasons that can be exposed and OOMKilled is part of them. See the [pod metrics documentation](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) for more information about that.

**Comment by Delorien84** [comment]
Sorry for this issue. I unintentionally create it in different project.
