### ISSUE TITLE
metric kube_pod_labels format wrong, is a change or bug?

### ISSUE THREAD

**Issue by hakur** [kubernetes/kube-state-metrics#1298]
**What happened**:
 kubernetes v1.19.2 && kube-state-metrics v2.0.0-alpha.2 metircs output without labels
![image](https://user-images.githubusercontent.com/12321972/98509498-469f0000-229c-11eb-97de-b9777fd7f67a.png)
 but kubernetes v1.19.2 && kube-state-metrics v1.9.7 metrics output is correctly with labels
![image](https://user-images.githubusercontent.com/12321972/98509837-ee1c3280-229c-11eb-9b1d-2bc7d5cb0803.png)
I have some prometheus query exp required these labels ,so is is a BUG or API change?or something missed in my kubernetes config?

**What you expected to happen**:
wish kube-state-metrics v2.0.x metrics can output labels
**How to reproduce it (as minimally and precisely as possible)**:
run kubernetes v1.19.2 and kube-state-metrics :v2.0.0-alpha.2,then curl get kube-state-metircs:8080/metrics
**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v2.0.0-alpha.2
- Kubernetes version (use `kubectl version`): v1.19.2
- Cloud provider or hardware configuration:
- Other info:

**Comment by lilic** [comment]
Hey! Some is bug and some is feature. For the bug see https://github.com/kubernetes/kube-state-metrics/issues/1270 and this should be fixed in the next version of kube-state-metrics prerelease.

As for the rest of the labels, this is expected, due to security and high cardinality issues we decided to by default we will only expose name and namespace labels for each of the kube_<>_labels. Rest you can to enable via the --labels-allow-list flag.

Hope that answers all your questions, thanks for testing and reporting!

**Comment by hakur** [comment]
> Hey! Some is bug and some is feature. For the bug see #1270 and this should be fixed in the next version of kube-state-metrics prerelease.
> 
> As for the rest of the labels, this is expected, due to security and high cardinality issues we decided to by default we will only expose name and namespace labels for each of the kube_<>_labels. Rest you can to enable via the --labels-allow-list flag.
> 
> Hope that answers all your questions, thanks for testing and reporting!

thank you very much, I understood.
should I close this issue?

**Comment by hakur** [comment]
![image](https://user-images.githubusercontent.com/12321972/98522499-bc609700-22af-11eb-8546-790bb0bd763d.png)
resolved
