### ISSUE TITLE
Strange value for kube_statefulset_status_replicas_current

### ISSUE THREAD

**Issue by HappyCerberus** [kubernetes/kube-state-metrics#1324]
Strange value for kube_statefulset_status_replicas_current. I believe this is related to: https://github.com/kubernetes/kube-state-metrics/issues/1057

I run into this with a prometheus alert that does `(kube_statefulset_status_replicas_ready / kube_statefulset_status_replicas_current) != 1`

On one of our clusters, `kube_statefulset_status_replicas_current` has value `0` for one of our services, even though it should be 2 by all accounts.

`kubectl describe` is producing the same values on both clusters.

```
Replicas:           2 desired | 2 total
Update Strategy:    OnDelete
Pods Status:        2 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

**Environment**:
- kube-state-metrics version: `quay.io/coreos/kube-state-metrics:v1.9.7`
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1200", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-01T09:20:59Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: gCloud

**Comment by Nerdsav** [comment]
вт, 15 дек. 2020 г., 20:05 RNDr. Simon Toth <notifications@github.com>:

**Comment by lilic** [comment]
@HappyCerberus Thanks for the report, do you think you can include the raw metrics from kube-state-metrics /metrics endpoint, just the ones about statefulset? Does this happen all the time or just once in a while? Also any logs from the kube-state-metrics container would be useful, thanks!

**Comment by HappyCerberus** [comment]
It seem to be specific to one stateful set in particular. It is very consistent, but again, only on one cluster.

    kube_statefulset_status_replicas_current{namespace="default",statefulset="mongo"} 0
    kube_statefulset_status_replicas_current{namespace="default",statefulset="prometheus-server"} 2

**Comment by eberkut** [comment]
I'm seeing the exact same issue with a newly deployed Kafka cluster (using Strimzi). Same kube-state-metrics version and same alert rule (which is in the popular https://awesome-prometheus-alerts.grep.to/rules.html) but on AWS EKS with Kubernetes 1.16.

```
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
kube_statefulset_status_replicas_current{app_kubernetes_io_name="kube-state-metrics",app_kubernetes_io_version="v1.9.7",cluster="REDACTED",instance="10.1.10.234:8080",job="kubernetes-service-endpoints",kubernetes_namespace="kube-system",kubernetes_service_name="kube-state-metrics",namespace="kafka",statefulset="my-cluster-kafka"}	0
kube_statefulset_status_replicas_current{app_kubernetes_io_name="kube-state-metrics",app_kubernetes_io_version="v1.9.7",cluster="REDACTED",instance="10.1.10.234:8080",job="kubernetes-service-endpoints",kubernetes_namespace="kube-system",kubernetes_service_name="kube-state-metrics",namespace="kafka",statefulset="my-cluster-zookeeper"}	3
kube_statefulset_status_replicas_current{app_kubernetes_io_name="kube-state-metrics",app_kubernetes_io_version="v1.9.7",cluster="REDACTED",instance="10.1.10.234:8080",job="kubernetes-service-endpoints",kubernetes_namespace="kube-system",kubernetes_service_name="kube-state-metrics",namespace="kafka",statefulset="prometheus-prometheus"}	1
kube_statefulset_status_replicas_current{app_kubernetes_io_name="kube-state-metrics",app_kubernetes_io_version="v1.9.7",cluster="REDACTED",instance="10.1.10.234:8080",job="kubernetes-service-endpoints",kubernetes_namespace="kube-system",kubernetes_service_name="kube-state-metrics",namespace="kube-system",statefulset="ebs-snapshot-controller"}	1
```

```
$ kubectl get statefulsets -n kafka
NAME                    READY   AGE
my-cluster-kafka        3/3     16h
my-cluster-zookeeper    3/3     16h
prometheus-prometheus   1/1     16h
```

```
$ kubectl describe statefulset my-cluster-kafka -n kafka
Name:               my-cluster-kafka
Namespace:          kafka
CreationTimestamp:  Wed, 16 Dec 2020 20:57:12 +0100
Selector:           strimzi.io/cluster=my-cluster,strimzi.io/kind=Kafka,strimzi.io/name=my-cluster-kafka
Labels:             app.kubernetes.io/instance=my-cluster
                    app.kubernetes.io/managed-by=strimzi-cluster-operator
                    app.kubernetes.io/name=kafka
                    app.kubernetes.io/part-of=strimzi-my-cluster
                    strimzi.io/cluster=my-cluster
                    strimzi.io/kind=Kafka
                    strimzi.io/name=my-cluster-kafka
Annotations:        strimzi.io/kafka-version: 2.6.0
                    strimzi.io/storage: {"volumes":[{"type":"persistent-claim","size":"100Gi","deleteClaim":false,"id":0}],"type":"jbod"}
Replicas:           3 desired | 3 total
Update Strategy:    OnDelete
Pods Status:        3 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

Deleting the kube-state-metrics deployment and recreating it doesn't fix the issue. No errors in the kube-state-metrics logs.

It looks similar the issue described in https://github.com/kubernetes/kube-state-metrics/issues/1170 which references https://github.com/kubernetes/kube-state-metrics/issues/694 as a potential root cause.

**Comment by lilic** [comment]
Hmm yes you are right it might be that bug. We have that on the plan for after we finish up the 2.0 release to really focus on it!

But what is interesting, if it was that bug this should have fixed the issue:

> Deleting the kube-state-metrics deployment and recreating it doesn't fix the issue.

Thanks for all the details, will try to dig up and see if I can reproduce this!

**Comment by JanKowalik** [comment]
I have the same issue. However I can see that yaml from `kubectl get sts <name> -o yaml` has values under `status` section for `replicas`, ` readyReplicas`, `updatedReplicas` but **not** for `currentReplicas`. Any idea why and how to fix that? 
Is it where metrics take it from?

**Comment by lilic** [comment]
Yes, you are right, we take it from currentReplicas. https://github.com/kubernetes/kube-state-metrics/blob/eba9142028841d5181ce09836fb1e0c2cf54f90c/internal/store/statefulset.go#L84

**Comment by harjas27** [comment]
I was able to reproduce this scenario where the current replicas is 0. I created a statefulset with `Update Strategy:    OnDelete` and 1 replica. Then I updated the image for the sts and manually deleted the pod. 
I noticed that the `currentRevision` is not equal to `updateRevision`.
There is a condition in the code https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L314 to check for the replicas with the version equal to `currentRevision`. Since the version of the replica is equal to `updateRevision`, the `replicaCount` is 0.
This is specific to the `OnDelete` strategy itself because for `RollingUpdate`, there is a function https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_utils.go#L376 which updates the `currentRevision` and `currentReplicas`

**Comment by lilic** [comment]
Thanks @harjas27 for that! What is your suggestion for the fix if any?

**Comment by harjas27** [comment]
@lilic as per this of currentReplicas(https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go#L177)
```
currentReplicas is the number of Pods created by the StatefulSet controller from the StatefulSet version indicated by currentRevision.
```
since the revision of the pods will not be equal to currentRevision, currentReplicas is 0. This is expected behaviour then

**Comment by dgrisonnet** [comment]
Awesome investigation @harjas27! As you said, this is expected behavior with the `OnDelete` strategy of statefulsets and thus I don't think there is anything to fix in kube-state-metrics directly.
That said, the statefulset metrics documentation [1] could maybe be improved to include a notice regarding this edge case. The official kubernetes documentation for the `OnDelete` strategy [2] could also be quoted to mention that this issue can be fixed by manually deleting the pod after updating the statefulset.

[1] https://github.com/kubernetes/kube-state-metrics/blob/master/docs/statefulset-metrics.md
[2] https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#on-delete

/remove-lifecycle stale

**Comment by fzyzcjy** [comment]
I am also seeing the same problem. Is there any updates? Thanks!

**Comment by stiliajohny** [comment]
/reopen

hey guys did we find a solution for this ?

**Comment by Haleygo** [comment]
Hello! @dgrisonnet 
>The official kubernetes documentation for the OnDelete strategy [2] could also be quoted to mention that this issue can be fixed by manually deleting the pod after updating the statefulset.

I don't think that will do the trick, statefulset controller only update `CurrentRevision` equal with `UpdateRevision` when [`UpdateStrategy` is RollingUpdate and all pods are updated](https://github.com/kubernetes/kubernetes/blob/6fed03ea91627185afd4976474a396f17689f0d7/pkg/controller/statefulset/stateful_set_utils.go#L589C20-L589C20). Issue still open in [kubernetes](https://github.com/kubernetes/kubernetes/issues/106055).

What do you think about counting `kube_statefulset_status_replicas_current` with `status.updatedReplicas+status.currentReplicas` instead of using `status.currentReplicas` or `status.updatedReplicas` alone when they are not equal?
Since that indicates statefulset been updated and I think users can consider pods with both revision are good ones.
