### ISSUE TITLE
Helm Repo does not exist

### ISSUE THREAD

**Issue by ryan-dyer-sp** [kubernetes/kube-state-metrics#1342]
**What happened**:
The helm repo indicated by documentation does not exist.
```
helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics
Error: looks like "https://kubernetes.github.io/kube-state-metrics" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes.github.io/kube-state-metrics/index.yaml : 404 Not Found
```

**What you expected to happen**:
I found multiple existing issues and PRs around this problem but they all appear to be closed or merged.  They all appear to point to it being a CD issue.  Can someone please do the needful to get this fixed?

**Comment by austinorth** [comment]
For reference, here are the other issues that have since been closed erroneously are https://github.com/kubernetes/kube-state-metrics/issues/1331 and https://github.com/kubernetes/kube-state-metrics/issues/1337. This issue breaks some scripts I have written for setting up k8s development environments.

Looking at the commit history, it looks like @lilic or @scottrigby may be able to help with this?

**Comment by austinorth** [comment]
For now, I have switched over to the Bitnami chart [here](https://github.com/bitnami/charts/tree/master/bitnami/kube-state-metrics) which works for my setup. May work as a temporary solution for you @ryan-dyer-sp

**Comment by chrissng** [comment]
Repo owners, 

The Kubernetes user community at large depends on the great work done by the developer community. KSM is a critical aspect of any Kubernetes cluster and hence it is expected that the user community treats this repository as the source code as well as the **_official_** helm repository. 

So to a certain degree there is urgency to set up the helm repository and make it available for public consumption. I am nudging the owners to get it done with for the benefit of the community as a whole. 

Thanks!

**Comment by lilic** [comment]
I am not a mantainer of the Helm chart so sadly cannot help here. @mrueg or @tariq1890 might be able to help better here.

**Comment by brancz** [comment]
Sorry, but neither @lilic or myself use helm at all. We accepted the helm chart files into this repo under the condition that someone that is not us maintains them. We are under no obligation to do so just because this promise was broken.

If @tariq1890 can't maintain it, and nobody steps up to do so, then we will be removing it. We'd love to work with Bitnami (or anyone else who would like to step up) if they would like to maintain the chart as part of the kube-state-metrics upstream project, but there is no incentive for us to do so, and frankly we don't owe anybody anything. If companies fail to invest in open source, and only take, then that's nobodies fault but their own.

**Comment by mrueg** [comment]
I am happy to help out here and continue maintaining it. @scottrigby has been helping out with setting up the chart in this repo. Currently, there are some issues with the prow integration on test-infra for gh-pages (see scott's comment here: https://github.com/kubernetes/kube-state-metrics/pull/1325#issuecomment-753517309). While work is being done to get the chart published, you can still use https://charts.helm.sh/stable and https://charts.helm.sh/stable/packages/kube-state-metrics-2.9.3.tgz No major changes were made to the chart since then and no new proper version of kube-state-metrics has been released.

@brancz @lilic let me know if you prefer a disclaimer on https://github.com/kubernetes/kube-state-metrics/blob/master/charts/kube-state-metrics/README.md that this is still WIP.

**Comment by lilic** [comment]
A WIP is a good start, agreed! Would be great to have that and clarify the location of the current chart as well while you all resolve it, thanks!!

**Comment by austinorth** [comment]
Thank you all so much for the super quick responses! Really appreciate all of your hard work. 🤗 @mrueg if there's any way I can help too, let me know! Much love.

**Comment by scottrigby** [comment]
#1347 is ready to be merged. Once the gh actions from merging that complete properly (it was able to push the `index.yaml` file), then we should be good to go on future chart PRs and can close this issue.

After that, we can merge #1335 to give users friendly info about the helm repo.
