### ISSUE TITLE
Two same metrics exist??

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/kube-state-metrics#147]
Hi, I deployed the kube-state-metrics according to the doc and find that there exists two different records for one same metric like kube_pod_container_status_restarts , only instance label is different?

{container="kube-controller-manager",instance="172.20.250.58:8080",job="kubernetes-service-endpoints",k8s_app="kube-state-metrics",kubernetes_name="kube-state-metrics",kubernetes_namespace="kube-system",namespace="kube-system",pod="kube-controller-manager-xs342"}
{container="kube-controller-manager",instance="172.20.27.196:8080",job="kubernetes-service-endpoints",k8s_app="kube-state-metrics",kubernetes_name="kube-state-metrics",kubernetes_namespace="kube-system",namespace="kube-system",pod="kube-controller-manager-xs342"}

Is it for HA purpose or some other purposes? Because I want to set up alert and don't want to get things duplicated?Thanks

**Comment by andrewhowdencom** [comment]
it looks like they're difference instances of the controller manager. Have you got two copies of those running on your cluster?

**Comment by brancz** [comment]
@WIZARD-CXY yes this is for HA purposes, there are two different approaches you can take here:

1) use a pessimistic approach when querying for kube-state-metrics, and perform for example doing something like:

```
max by(namespace, pod) (kube_pod_container_status_restarts)
```

2) Just run a single instance of kube-state-metrics.
3) Instead of whitebox monitoring kube-state-metrics put it behind a service and load balance to the instances. As kube-state-metrics is really about cluster metrics, this is not an anti pattern in this case.

All of these have their trade-offs, you'll just have to decide what suits you best. In most cases I would say running a single instance should be perfectly fine.

**Comment by WIZARD-CXY** [comment]
@andrewhowdencom I have only one instance of controller-manager, the instance label represents state-metrics pod, not controller-manager

**Comment by WIZARD-CXY** [comment]
@brancz aha I agree that "running a single instance should be perfectly fine" too
