### ISSUE TITLE
/var/run/secrets/kubernetes.io/serviceaccount/ca.crt not found error. 

### ISSUE THREAD

**Issue by gabbar023** [kubernetes/kube-state-metrics#1510]
![image](https://user-images.githubusercontent.com/58171832/123260011-c10e4e80-d512-11eb-9ebb-ec739a5c5ec3.png)

I tried to scrape metrics from openshift-prometheus to another prometheus-server using servicemonitors.

I am getting ca.crt not found error from another prometheus server.
How do i scrape kube-state metrics from openshift-prometheus to a new prometheus-server.

**Comment by lilic** [comment]
Hey, this is more of a question for openshift support team rather than kube-state-metrics project. But since I worked on that in the past, the short answer is: that is not supported, you need to deploy a new kube-state-metrics in your own namespace or enable user workload monitoring. 

Closing as it's not related to this project, for more info please reach out to red hat OpenShift monitoring team.
