### ISSUE TITLE
Consider removing metrics with cAdvisor overlap

### ISSUE THREAD

**Issue by PhilipGough** [kubernetes/kube-state-metrics#1539]
With the goal of reducing the number of series per scrape, would we consider the removal of metrics that overlap with that of `cAdvisor`, after initial investigation I can see at least the following:

`kube_pod_container_state_started ` provides a subset of data from  `container_start_time_seconds ` when queried by pod and container.

```json
{
          "metric": {
            "__name__": "kube_pod_container_state_started",
            "container": "prometheus",
            "endpoint": "https-main",
            "job": "kube-state-metrics",
            "namespace": "openshift-monitoring",
            "pod": "prometheus-k8s-0",
            "service": "kube-state-metrics"
          },
          "value": [
            1627032311.791,
            "1627018115"
          ]
       }
  }
```

compared to 

```json
      {
        "metric": {
          "__name__": "container_start_time_seconds",
          "container": "prometheus",
          "endpoint": "https-metrics",
          "id": "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podfc3ad02f_7eb0_4e5f_a483_6bdd7563df37.slice/crio-047b38053fd6cf56e8e35ab443888823b7090171b24a36e1535fee9ffc118ca8.scope",
          "image": "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:02283c8ebcb6a2b9b3c5133af370df572cedfb19bcc1361e6451be46516f46bd",
          "instance": "10.0.146.89:10250",
          "job": "kubelet",
          "metrics_path": "/metrics/cadvisor",
          "name": "k8s_prometheus_prometheus-k8s-0_openshift-monitoring_fc3ad02f-7eb0-4e5f-a483-6bdd7563df37_0",
          "namespace": "openshift-monitoring",
          "node": "ip-10-0-146-89.ec2.internal",
          "pod": "prometheus-k8s-0",
          "service": "kubelet"
        },
        "value": [
          1627033829.683,
          "1627018115"
        ]
      }
}
```

The following seems to map also:

 `kube_pod_container_resource_limits` ->  (`container_spec_memory_limit_bytes`, `container_spec_cpu_shares`)

There may be more overlap, but I just wanted to ask the question to see if this is something that was worth pursuing?

**Comment by lilic** [comment]
Hey. A lot of our users expect these metrics to be there and are used for alerts, dashboards, etc. If you need to remove them you can always use the flag `--metric-denylist ` or drop them in Prometheus. But these are stable metrics, and also I don't think kube_pod_container_resource_limits is the same as container_spec_memory_limit_bytes.

**Comment by paulfantom** [comment]
Some clarification for whoever finds this in the future as a lot of information was not published in discussion:
- `kube_pod_container_resource_limits{container="XYZ",resource="memory"}` maps 1:1 into `container_spec_memory_limit_bytes{container="XYZ"}`
- `kube_pod_container_resource_limits{container="XYZ",resource="cpu"}` maps indirectly to `container_spec_cpu_quota{container="XYZ"}` and `container_spec_cpu_period{container="XYZ"}`
- `kube_pod_container_resource_requests{resource="memory"}` doesn't have a counterpart in cgroups (or rather I couldn't find it)
- `kube_pod_container_resource_requests{resource="cpu"}` maps indirectly to `container_spec_cpu_shares{container="XYZ"}`

The above is taken from https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run and https://man7.org/linux/man-pages/man7/cgroups.7.html plus experimentation :)

In all the above cases, the additional difference is that data from KSM is a declared state taken from apiserver, whereas `container_.*` metrics are observed state taken directly from kubelet.

Additional notes:
- Since k8s 1.21 kube-scheduler is also able to expose resource information - https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#kube-scheduler-metrics as per [KEP1748](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1748-pod-resource-metrics) (when those hit GA we should take a look how to switch alerts and dashboards to use them)
- cgroups v2 should give a better interface and make KSM resource metrics potentially obsolete. But that's a topic for ~2023 :)

**Comment by lilic** [comment]
> (when those hit GA we should take a look how to switch alerts and dashboards to use them)

Yes that is more for kube-prom rather than kube-state-metrics here :) The issue is that not all users have admin power to enable those on that level, so this is where kube-state-metrics comes into play.

**Comment by PhilipGough** [comment]
Thanks @lilic closing based on your explanation.
