### ISSUE TITLE
Not seeing reason for failure on all kube_job_status_failed queries

### ISSUE THREAD

**Issue by kherrmann3** [kubernetes/kube-state-metrics#1638]
**What happened**: 
When I do a global search of `kube_job_status_failed` inside of prometheus I'm getting some results that don't have the reason in them.

I'm not exactly sure what the numerical return indicates for this metric. I first thought it indicated the metric was live, but it didn't make sense since the metric instance should only show if the job failed, correct? 

When the value is 1, I've only seen 2 kinds of results, 1 where there is no `reason` label and 1 where the reason=="BackoffLimitExceeded". When the value is 0 I see 4 kinds of results: no `reason` shown (not null, the label just isn't there), "BackoffLimitExceeded", "DeadlineExceeded", "evicted". 

**What you expected to happen**: 
I would expect every return of `kube_job_status_failed` to provide a reason label. And I would expect to see all types of reasons, regardless of the gauge value being `0` or `1`.

**How to reproduce it (as minimally and precisely as possible)**: 
Create a cronjob that will fail for various reasons, and have it run regularly, and you should see several instances of this metric go live.

**Anything else we need to know?**:
From the kube-state-metrics log, not seeing any errors. 
```
Active resources: cronjobs,daemonsets,deployments,endpoints,ingresses,jobs,limitranges,namespaces,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,services,statefulsets
```

**Environment**:
- kube-state-metrics version: 2.2
- Kubernetes version (use `kubectl version`): version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.15-gke.500"}
- Cloud provider or hardware configuration: Google/GKE
- Other info:

**Comment by harjas27** [comment]
The metric gives `The number of pods which reached Phase Failed and the reason for failure`, so the value is the number of pods which failed because of that particular reason. When you are seeing value :-
* 1 - one pod failed, if the reason label is empty it means that the reason is unknown else the reason label indicates the reason for failure
* 0 - none of the pod failed for the given reason. If the reason label is not present, it means that no pod for that job failed.
 
 Having said that, I have another doubt from the code itself. While computing the number of pods failed for a particular known reason, why do we return only 1 or 0 ?
 https://github.com/kubernetes/kube-state-metrics/blob/0c9580d09c6ac8b35630813afbcc0fe217ce1874/internal/store/job.go#L212-L215
@dgrisonnet

**Comment by dgrisonnet** [comment]
There definitely seems to be something wrong with this metric. I personally wouldn't expect `kube_job_status_failed` to report any reason since there might be multiple pods that failed with different failure reasons. It should be only responsible for reporting `The number of pods which reached Phase Failed` as the `kube_job_status_succeeded` metric is doing for succeeded jobs.

If the reason is really meaningful, we might prefer introducing it in a `kube_job_status_conditions_failed` metric that would contain all the conditions that failed and the reasons for their failures.
