### ISSUE TITLE
kube_node_status_allocatable does not appear to be updating the difference of allocatable resources

### ISSUE THREAD

**Issue by tbaumann-sf** [kubernetes/kube-state-metrics#1658]
**What happened**:
I am trying to plot the number of resources available on each of my kubernetes nodes in my cluster and unable to get the metric to change.  When I grab the value of kube_node_status_allocatable {resource= memory | cpu | pods } the value never changes over what it was initialized to (in my case 58).  

**What you expected to happen**:
I would expect to be able to grab the metric value for kube_node_status_capacity { resource= memory | cpu | pods } as the max value.  I would then expect that I could take the kube_node_status_allocatable value for the resource and subtract it from the capacity to get consumed.  I only ever see the max value in both kube_node_status_capacity and kube_node_status_allocatable.  

**How to reproduce it (as minimally and precisely as possible)**:
Take a kubernetes cluster with 2.3.0 kube-state-metrcs, spin up pods on a few nodes and see if you can get the metric to report anything other than the max value.  

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 1.8.0 and 2.3.0
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19" Server Version: version.Info{Major:"1", Minor:"21+"
- Cloud provider or hardware configuration: aws
- Other info:

**Comment by fpetkovski** [comment]
Hi @tbaumann-sf, I think you might be running into expected behavior. The allocatable field in the node status indicates how much of a particular resource can Kubernetes use to schedule pods on that node. However, that value is not affected by how many pods are already scheduled, it merely indicates what portion of the node's resource is usable by the scheduler. 

This link from the official documentation might be helpful: https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#node-allocatable

**Comment by tbaumann-sf** [comment]
Fair enough, I was expecting it to go down based off of allocations.  I think I need to look into kubelet metrics for this.
