### ISSUE TITLE
CVE-2020-26160 - kube-state-metrics:v1.9.7

### ISSUE THREAD

**Issue by dugalp** [kubernetes/kube-state-metrics#1673]
Hi,

We would like to know if the CVE (https://nvd.nist.gov/vuln/detail/CVE-2021-38297) for jwt-go in version 3.2.0 is on the cards for resolution? We are an enterprise and would like to get some help with removing the vulnerability from the minor version. If you could help make a new minor version with the fix, that would be grand!

-Patrick

**Comment by fpetkovski** [comment]
Since this is a transitive dependency, it might be a bit challenging to fix it. 
It looks like the latest client-go still uses autorest/adal@v0.9.13[1], a release from 2019, which depends on jwt-go@3.2.0[2].

[1] https://github.com/kubernetes/client-go/blob/master/go.mod#L10
[2] https://github.com/Azure/go-autorest/commit/42fde3a09860e638198648a4b285f31c483752cf#diff-ab41db5de6362b311d24dab46562baba8dad5e20fa5b9e25de14c426b4823654R20-R21

So maybe this issue is a better candidate for the kubernetes/client-go repository?
