### ISSUE TITLE
 duplicated metrics using kube-state-metrics sharding with --use-apiserver-cache

### ISSUE THREAD

**Issue by m-messiah** [kubernetes/kube-state-metrics#1679]
**What happened**:
Running kube-state-metrics in shards with enabled `--use-apiserver-cache` resulted in having constantly growing metrics which are not related to actual data.

**What you expected to happen**:
Correct sharding with reduced apiserver latency

**How to reproduce it (as minimally and precisely as possible)**:
1. Start more than 1 shard of kube-state-metrics.
  deployment0: `--shard=0 - --total-shards=2 --use-apiserver-cache`
  deployment1: `--shard=1 - --total-shards=2 --use-apiserver-cache`
2. Scrape through servicemonitor from examples.
3. Continuously start and stop some deployments.
4. Check `count by (pod) (kube_pod_info)` in prometheus

**Anything else we need to know?**:
When I removed the flag `--use-apiserver-cache` the counters dropped to good values.
<img width="2325" alt="image" src="https://user-images.githubusercontent.com/2103030/152810546-a8ac1c7c-20a5-48bb-af6b-38b1c5101ebe.png">

Probably related to https://github.com/kubernetes/kube-state-metrics/issues/1166

**Environment**:
- kube-state-metrics version: 2.3.0
- Kubernetes version (use `kubectl version`): v1.19.13

**Comment by dgrisonnet** [comment]
This might be because the mechanism we rely on to serve cached data from the apiserver is vulnerable to stale reads: https://github.com/kubernetes/kubernetes/issues/59848. I think it is not emphasized enough in the help text that this flag should be used with care because of that.

That said, do you know if this is replicable with only one instance of kube-state-metrics? Because it looks like there are way more stale data then what I would have expected.

**Comment by jpdstan** [comment]
We're seeing the same thing https://github.com/kubernetes/kube-state-metrics/issues/1569

**Comment by dgrisonnet** [comment]
@jpdstan you were seeing the same problem without sharding right?

**Comment by jpdstan** [comment]
@dgrisonnet this is with sharding as well. 10 pods, approx 500k unique metrics each

**Comment by fpetkovski** [comment]
I wonder if we have a bug in https://github.com/kubernetes/kube-state-metrics/blob/main/pkg/sharding/listwatch.go. 

Does the issue happen without sharding?

**Comment by JohnRusk** [comment]
@dgrisonnet 
> This might be because the mechanism we rely on to serve cached data from the apiserver is vulnerable to stale reads: https://github.com/kubernetes/kubernetes/issues/59848.

I see that K8s issue has been recently updated to say that the problem is solved for cases where the client component (e.g. kube-state-metrics) stays running.  E.g. if it stays running but fails over to a different API server instance then the problem won't happen (as long as it uses the Informer class).

But if the component itself restarts, the problem may still happen.

Does that recent update change the seriousness of the stale read problem, for kube-state-metrics?

**Comment by e-ngo** [comment]
@fpetkovski 
Does anyone have the context as to why we set RV = 0 in the Watch method despite the Reflector setting this RV For us after the initial List?
Code for reflector: https://github.com/kubernetes/client-go/blob/v0.22.0/tools/cache/reflector.go#L401-L415
Offending lines: https://github.com/kubernetes/kube-state-metrics/blob/008bdb1dc7bc6e0e0dd088ae140b45fd458083e0/pkg/watch/watch.go#L97-L99
I feel like this is a bug.

**Comment by dgrisonnet** [comment]
@e-ngo this indeed seems like a bug, good catch

**Comment by dgrisonnet** [comment]
Could any of you perhaps try to see if the bug still exists after the fix made by @e-ngo? This image contains it: https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics/global/kube-state-metrics@sha256:126f7ef47ac7723b19cc9bc6a3d63c71bcd87888cd4c12e0101684a2eb7ca804/details

**Comment by jpdstan** [comment]
i've tried the patch from @e-ngo , and using the query `count by (cluster_name, namespace, pod) (kube_pod_info{pod_ip=~".+"}) > 1`, it seems like the stale metrics are not happening anymore! i think we can close out this issue.
