### ISSUE TITLE
Readme clarification regarding authentication/authorization

### ISSUE THREAD

**Issue by paologallinaharbur** [kubernetes/kube-state-metrics#1714]
**What happened**:
I read the readme and I was a bit confused :trollface: 

**What you expected to happen**:
Not to be confused

---

Jokes apart checking the readme I found this sentence:
 >[...] plus kube-state-metrics in most cases has special authentication and authorization requirements as it essentially grants read access through the metrics endpoint to most information available to it.
 - Is still correct to say that "in most cases has special authentication and authorization is required"? 
 - Can any authentication and authorization (in front of the ksm endpoint) supported by ksm/k8s be configured? 
 - Can we configure authentication through bearer tokens?
I check past issues and I found [this one ](https://github.com/kubernetes/kube-state-metrics/issues/381
) (4y old) saying basically that there was not and suggested a different auth method https://github.com/brancz/kube-rbac-proxy

**Comment by fpetkovski** [comment]
Hello 👋 

> Is still correct to say that "in most cases has special authentication and authorization is required"?

I agree this can be a bit confusing. What that sentence is trying to say is that KSM exposes lots of information about resources in the form of metrics and anyone with access to the endpoint can see that information. However, whether authn/authz is required is really up to the user to decide. 

> Can any authentication and authorization (in front of the ksm endpoint) supported by ksm/k8s be configured?

Yes, an example would be deploying a basic-auth proxy as a sidecar. You can use 127.0.0.1 as the bind address when starting KSM so that the metrics endpoint is only accessible by the sidecar. However, KSM has no built-in authentication mechanisms at the moment.

> Can we configure authentication through bearer tokens?
> I check past issues and I found https://github.com/kubernetes/kube-state-metrics/issues/381(4y old) saying basically that > there was not and suggested a different auth method https://github.com/brancz/kube-rbac-proxy.

Correct, using kube-rbac-proxy would still be the recommended solution for this case.

**Comment by paologallinaharbur** [comment]
Ok thanks! 👍 
I wanted just to clarify if the info reported in those issues were still updated. 
I'll close the issue :)
