### ISSUE TITLE
For some sets of metrics, export each set as a single metric.

### ISSUE THREAD

**Issue by syedashrafulla** [kubernetes/kube-state-metrics#173]
The advantage of such a compaction of metrics is
- users can aggregate (say, in Stackdriver) rather than relying on a separate "total" metric,
- all the interesting metrics can be returned in one fetch rather than multiple fetches,
- the metrics can end up in the same shard for sharded monitoring solutions such as Stackdriver, and
- the metrics are more clearly defined by measurement instead of measurement and descriptors, which makes graphs in Stackdriver clearer.

Here are a few suggestions from the [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/tree/master/Documentation) documentation:

Metrics | New metric name | New Label | Label Values
-|-|-|-
[DaemonSet](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/daemonset-metrics.md) | `kube_daemonset_count` | `status` | `{Scheduled, Pending, Misscheduled, Ready}`
[Deployment](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/deployment-metrics.md) | `kube_deployment_status_replicas` | `status` | `{Available, Unavailable, Updated}`
[Job](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/job-metrics.md) | `kube_job_count` | `status` | `{Active, Succeeded, Failed}`
[Pod](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/pod-metrics.md) | `kube_pod_status_phase` | `phase` | `{Pending, Ready, Scheduled, Running, Succeeded, Failed, Unknown}`
[Pod](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/pod-metrics.md) | `kube_pod_container_info` | `status` | `{Waiting, Running, Ready, Terminated}`
[ReplicaSet](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/replicaset-metrics.md) | `kube_replicaset_count` | `status` | `{Ready, Fully Labelled}`
[ReplicationController](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/replicationcontroller-metrics.md) | `kube_replicationcontroller_replica_count` | `status` | `{Ready, Fully Labelled, Available}`

If I've mistakenly assumed two label values are mutually exclusive, using multiple labels still seems better than encoding label values in the metric name for the advantages described above.

**Comment by brancz** [comment]
Why the metrics are the way they are is because we wanted to consistently name the metrics by the keys of the kubernetes objects, I'm open to changing this, but its quite breaking and invasive, so I want to make sure we're actually gaining a lot from this if we do end up implementing it:

> users can aggregate (say, in Stackdriver) rather than relying on a separate "total" metric,

I don't understand this point, can you elaborate?

> all the interesting metrics can be returned in one fetch rather than multiple fetches,

This highly depends on the query language and the underlying system, in PromQL you can query by regex. The next monitoring system can only query by exact label matches (eg. will even with the proposed changes have to perform multiple queries).

> the metrics can end up in the same shard for sharded monitoring solutions such as Stackdriver, and

This is a great point! However, also highly depends and assumes how the underlying system performs sharding.

> the metrics are more clearly defined by measurement instead of measurement and descriptors, which makes graphs in Stackdriver clearer.

By definition of this point, it only applies to StackDriver (coincidently it also applies to Prometheus).
