### ISSUE TITLE
Replace CLI toolkit

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#1791]
Currently we're using pflag to parse arguments. This comes with a certain simplicity, a more sophisticated toolkit like viper/cobra or others would allow users to use other methods to configure KSM as well.
In particular an idea, that came up for the CustomResource Collector is to use EnvironmentVariables or a Configuration File based approach.

**Comment by rexagod** [comment]
If I understand the ask here correctly,  `--custom-resource-state-config-file`allows you to do just that (file-based input).

**Comment by mrueg** [comment]
The request here is to look into https://github.com/spf13/viper or similar libraries that have built-in support for a likely yaml-based config.

**Comment by rexagod** [comment]
This issue is divided into the following sub-issues (after discussing with @dgrisonnet).
* Incorporate `cobra`: https://github.com/kubernetes/kube-state-metrics/pull/1834
* Incorporate `viper`: https://github.com/kubernetes/kube-state-metrics/pull/1827
* Future plans (after v3.0): https://github.com/kubernetes/kube-state-metrics/issues/1738#issuecomment-1241802049

**Comment by mrueg** [comment]
I think this issue is resolved. Thanks for your work @rexagod
