### ISSUE TITLE
self metrics leak Go pointer types to the output

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kube-state-metrics#1824]
**What happened**:

ksm self-metrics endpoint is showing results such as:
```
HELP kube_state_metrics_list_total Number of total resource list in kube-state-metrics
TYPE kube_state_metrics_list_total counter

kube_state_metrics_list_total{resource="*v1.CertificateSigningRequest",result="success"} 5
kube_state_metrics_list_total{resource="*v1.ConfigMap",result="success"} 5
kube_state_metrics_list_total{resource="*v1.DaemonSet",result="success"} 4
```

where the `resource` label on the Prometheus metric reflects the fact Go pointer types are used here (e.g. `*v1.DaemonSet`).

The fact that the value contains `*` :
1. makes this metric less future-proof: what if someone changes the code in a way that this is no longer a pointer? there does not seem to be any tests covering this.
2. causes ingestion/querying issues on alternative time-series backends/APMs where `*` literal is used as a _wildcard_ character.

**What you expected to happen**:

`resource` field should be normalized to something independent of the underlying implementation details (e.g. `v1/DaemonSet`, or `v1.DaemonSet`, or whatever else is appropriate).

**How to reproduce it (as minimally and precisely as possible)**: 

Query the specified telemetry-host:telemetry-port. An example is [illustrated in the readme](https://github.com/kubernetes/kube-state-metrics/tree/734389481ab1a47422f07e80ef93b4359cadbaed#kube-state-metrics-self-metrics).

**Anything else we need to know?**:

This is happening because of `reflect.TypeOf(expectedType).String()` [here](https://github.com/kubernetes/kube-state-metrics/blob/734389481ab1a47422f07e80ef93b4359cadbaed/internal/store/builder.go#L532).

Happy to drive a change if maintainers agree this is worth changing. 

**Environment**:
- kube-state-metrics version: since 1.8.0 (introduced in 21b1f612856441271e497cdffd11784235434c26)
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Other info: N/A

**Comment by rexagod** [comment]
1. In case someone changed `expectedType`'s type, we'd simply have that type shown in the resource field.
2. This is a bigger concern for me TBH, and I'm +1 on avoiding `*` from all label values. However this will need to be thought out well, in order to maintain consistency across how different types are displayed, and the obvious fact that it should not be uncomfortable when working with different backends.

**Comment by mrueg** [comment]
This is still something we should look into @kubernetes/kube-state-metrics-maintainers

**Comment by Richabanker** [comment]
This looks like a reasonable change to have, we shouldn't be using wildcard characters in metric labels. @ahmetb could you add a PR (looks like you have identified the location where the change/s need to be done) ?

**Comment by Richabanker** [comment]
cc @dgrisonnet for his thoughts on this.

**Comment by dgrisonnet** [comment]
That is reasonable to me for the following reasons:
- from an ingestion standpoint, it is backward compatible to update label values 
- these are self metrics, so kms repo should be the main source for dashboard/alerts based on these so it is unlikely to break anyone

As long as we have a note in the changelog, I am fine with it.

**Comment by ahmetb** [comment]
Correct. I assume this is still a breaking change, however?

**Comment by Richabanker** [comment]
I would think, based on @dgrisonnet's response, maybe not? We will be updating the string value to another value and not really change the type altogether.

**Comment by ahmetb** [comment]
But if I have a monitoring alert set to collecting a metric like

    collection_errors{label=foo}

and the value is changed foo → bar, that breaks my alert silently (I never encounter any alerts firing anymore because the time series now doesn't exist)?

**Comment by logicalhan** [comment]
> Correct. I assume this is still a breaking change, however?

This is not a breaking change. A chart like

```
collection_errors{label=foo}
```

Will return zero timeseries but will be a valid alert. Changing the label-name however, would mean that the alert was itself was actually broken.

**Comment by Richabanker** [comment]
also looking at [Metrics Stability levels](https://kubernetes.io/blog/2021/04/23/kubernetes-release-1.21-metrics-stability-ga/#what-are-the-stability-levels-for-metrics), it seems label value changes are acceptable. We should go ahead with the fix.

**Comment by dgrisonnet** [comment]
> This is not a breaking change. A chart like

If we take this literally, it is a breaking change since it could create issues that were not present before that change in the users infrastructure. Existing alerts, dashboards or really any kind of consumers that assume a certain value could be broken after that change.

I've experienced scenarios where SLO alerts were broken by latency bucket changes and it is clearly not because the alert was invalid but rather because the alert needed to be updated to align with more recent standards. Although the alert being broken didn't cause any harm to the monitoring infrastructure directly, having it invalid broke a very critical part of the cluster observability.

My personal thought on that is that label values often need to be updated for various reasons that are hard to control, but instead of preventing ourselves from making improvements, we should make sure that changes are documented and that we try to keep alerts and dashboards as close as possible to the projects so that in case something like that open, the chance of breaking anything is very slim.

Another thing to keep in mind is that some values are meant to be used directly, some other are not. If we take the following timeserie as an example:
```
kube_state_metrics_list_total{resource="*v1.DaemonSet",result="success"}
```
It is unlikely for the `resource` label to be used directly in an alert or a dashboard since we shouldn't need to constantly measure the number of list call made to a particular resource, however, result could very well be used in directly in an alert to make sure that we keep the number of errors in check. Which is what we are doing here: https://github.com/kubernetes/kube-state-metrics/blob/6eadca823ec7bbc1fb2a601db46bc45288616988/examples/prometheus-alerting-rules/alerts.yaml#L9

**Comment by dgrisonnet** [comment]
So my tl;dr is that this particular change is very unlikely to be a breaking change, but it could always be worth mentioning it in the changelog.

**Comment by ahmetb** [comment]
Reasonable. I have nothing to lose in this case and wanted to play devil's advocate for users who might have written alerts that specifically spelling out the label value. It's a long shot for this metric, I assume people use aggregated views to alert on these.
