### ISSUE TITLE
kube_node_status_condition   The condition "instance " is the pod ip rather than the ip of the host

### ISSUE THREAD

**Issue by looknicemm** [kubernetes/kube-state-metrics#1872]
![image](https://user-images.githubusercontent.com/32831481/198527550-f29f9aeb-204f-4b47-9ab5-07e12d2fa51f.png)

kube_node_status_condition   The condition "instance " is the pod ip rather than the ip of the host

**Comment by rexagod** [comment]
/unassign
@looknicemm Are you sure this is not the expected behavior (is `honor_labels: false` on your end)? The [`instance`](https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series) label is something that usually auto-generated, and I'm fairly sure we do not override this.

**Comment by dgrisonnet** [comment]
The `instance` label comes from your Prometheus scraping configuration, most likely from prometheus-operator if you are using a ServiceMonitor or PodMonitor to scrape kube-state-metrics. As explained in this Promehteus doc: https://prometheus.io/docs/concepts/jobs_instances/, the instance refers to the endpoint of the scrape target so in this case, the endpoint on which kube-state-metrics is exposing metrics.

Since this is unrelated to kube-state-metrics, I am closing the issue.
