### ISSUE TITLE
About this metric "kube_persistentvolumeclaim_status_phase", is there another status called "Terminating"? help wanted

### ISSUE THREAD

**Issue by mumong** [kubernetes/kube-state-metrics#1912]
there is  a problem, if i dedelte the pvc but haven't delte the pod yet. this pvc will going to be like this status "Terminating".so whethere the metric "kube_persistentvolumeclaim_status_phase" can detect the status or only "Bound/Lost/Pending"?

![微信图片_20221128105639](https://user-images.githubusercontent.com/91200009/204182027-5876fd1e-da2e-4d55-b6cd-29bfb9cf95c9.jpg)

**Comment by fpetkovski** [comment]
Currently we only report these three distinct phases that you described in the issue. The code which does this is here: https://github.com/kubernetes/kube-state-metrics/blob/master/internal/store/persistentvolumeclaim.go#L118

**Comment by mumong** [comment]
> Currently we only report these three distinct phases that you described in the issue. The code which does this is here: https://github.com/kubernetes/kube-state-metrics/blob/master/internal/store/persistentvolumeclaim.go#L118

thanks so much,is there going to add the status in the future? or the metric didn't cover this status when design it ? :) 
anyway than you

**Comment by fpetkovski** [comment]
This particular metric does not cover Terminating because that is not a phase: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#phase.

I believe the `Terminating` message is inferred by `kubectl describe` and is not an actual field in the PVC status. It relies on various fields in the PVC phase to infer the status: https://github.com/kubernetes/kubectl/blob/cf0626ffbf4e4f8e9a7abaf557c69b8761b0b34b/pkg/describe/describe.go#L1520

**Comment by dgrisonnet** [comment]
This issue has been answered in https://github.com/kubernetes/kube-state-metrics/issues/1912#issuecomment-1330519707.

**Comment by mumong** [comment]
thanks everyonve
/close
