### ISSUE TITLE
Breaking changes in 2.7.0 with hpa metrics and Kubernetes 1.22

### ISSUE THREAD

**Issue by dankolt** [kubernetes/kube-state-metrics#1946]
After merge #1906 hpa metrics can't collect from Kubernetes 1.22.
Kube-state-metrics logs tells that object *v2 HorizontalPodAutoscaler is undefined.
If it's expected behavior, then I guess need some note in release notes that minimal support k8s version is 1.23.

**Comment by razum2um** [comment]
Confirm this issue, k8s-1.22, prometheus-operator-kube-state-metrics-2.7.0 logs:
```
W0109 13:24:32.432243       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: failed to list *v2.HorizontalPodAutoscaler: the server could not find the requested resource
E0109 13:24:32.432271       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: Failed to watch *v2.HorizontalPodAutoscaler: failed to list *v2.HorizontalPodAutoscaler: the server could not find the requested resource
```
so for 1.22 the proper kube-state-metrics version is 2.6.0

p.s. and the maximum compatible chart of `prometheus-operator` is `kube-prometheus-stack-42.0.3`

**Comment by mrueg** [comment]
I assume v2beta2 support got dropped and v2 got introduced in v1.23 (https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#horizontalpodautoscaler-v2-graduates-to-ga).

See: https://github.com/kubernetes/kube-state-metrics/pull/1906

https://github.com/kubernetes/kube-state-metrics#compatibility-matrix


Since kubernetes 1.22 has already reached EOL upstream (https://kubernetes.io/releases/patch-releases/#non-active-branch-history), I would suggest to upgrade your clusters.

**Comment by razum2um** [comment]
Agree on upgrading, but worth mentioning a lot of people running in the cloud, in particular in aws/eks, where [EOLs lagging behind by ~2 upstream versions](https://endoflife.date/amazon-eks), i.e. 1.22 is EOL in 3 months and released just 9 months ago

**Comment by mrueg** [comment]
I can see your point, and you might want to talk to your public cloud provider to help out here.
If cloud vendors support EOL versions of Kubernetes for a longer time, they are more than welcome to contribute to the project.

**Comment by dashpole** [comment]
1.22 is ancient at this point, so this probably isn't relevant anymore

/close
