### ISSUE TITLE
Expose metrics for Pod readiness gates

### ISSUE THREAD

**Issue by alexku7** [kubernetes/kube-state-metrics#1981]
Hello

Sometimes a Pod has to pass the readiness gates in order to become "really" ready.
For example : [AWS LB readiness gate)](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/pod_readiness_gate/#checking-the-pod-condition-status)

Currently the Pod seems as Ready from he kubernetes perspective but actually the pod isn't ready  as long as he doesn't pass all readiness gates.

The problem that all current metrics show that the pod is in the ready state but the pod is actually non-ready. 
There are no metrics which can signal us that the pod isn't ready. If something is wrong, the pod is stuck in non-ready state forever and no way to recognize it unless we check it manually by kubectl describe pod.

Not sure if the problem in the kube control plane or just because the kube metrics doesn't"t expose the appropriate metric.

**Comment by dgrisonnet** [comment]
The problem is that this is not the Kubernetes way to report pod readiness. Adding a new reason breaks all the assumption that a "Ready" pod is actually ready. Normally you would add a readiness probe that would dictate whether you pod is ready or not and update the reason accordingly. Since the `Elb.InitialHealthChecking` reason is not native, I would be against adding it to the list of reasons we expose in kube-state-metrics.

I would encourage you to reach out to your AWS representative and check with them if they have a metric you can use instead.
