### ISSUE TITLE
Reduce agent memory by only caching needed k8s object fields

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/kube-state-metrics#2012]
**What would you like to be added**: Only cache needed k8s object fields, not all fields. For example, .status

**Why is this needed**: KSM agent memory is high even if only exposing one pod metric. Because it stores all pod fields in cache, if I understand correctly.

**Describe the solution you'd like**
When metrics allowlist is set, the cache only stores needed fields.
If metrics allowlist is changed, it should still work.

**Additional context**

**Comment by dgrisonnet** [comment]
Which caching are you referring to? The one from the informers or the one where ksm stores the metrics?

**Comment by CatherineF-dev** [comment]
The one from the informers

**Comment by CatherineF-dev** [comment]
Just realized that it already stores metrics generated based on those objects, instead of storing entire Kubernetes objects.
https://github.com/kubernetes/kube-state-metrics/blob/main/pkg/metrics_store/metrics_store.go#L28-L30

 Still in thinking why kube-state-metrics memory is around 200MiB for about 10000pods. Expect a smaller number.

**Comment by dgrisonnet** [comment]
Actually, I looked at the code again to refresh my memory and we don't have any informers for the resources we want to expose metrics from. We have reflectors that directly transform the objects into the corresponding metrics and put that raw metric data in the metrics cache: https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/builder.go#L537-L548

The reasoning behind caching the generated metrics is to reduce the metric collection and CPU usage. This is a trade-off that was necessary to make in order to have low scrape duration. If you are interested, you can read more about it in: https://github.com/kubernetes/kube-state-metrics/blob/main/docs/design/metrics-store-performance-optimization.md.

> Still in thinking why kube-state-metrics memory is around 200MiB for about 10000pods. Expect a smaller number.

I would expect the current memory utilization of ksm to tend to the size of the request body from the /metrics endpoint at scale, so I don't think that 200MiB is unreasonable here.
