### ISSUE TITLE
CustomResourceState move from GroupVersionKind to GroupVersionResource

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#2093]
**What would you like to be added**:
Currently the configuration requires to set a Group, a Version and a Kind, CRS should either move to or additionally accept a Group Version Resource option.
**Why is this needed**:
We run into issues with pluralizing the kind and if we use resources, we also can generate RBAC roles from the existing CRS config without figuring out what resource we need to attach it to.
**Describe the solution you'd like**

Ideally we drop the Kind and make it GroupVersionResource to limit the scope effectively. This is breaking existing configs, but it's an experimental feature, so we can still iterate on it.

**Additional context**

**Comment by logicalhan** [comment]
great!

/triage accepted
/assign @rexagod

**Comment by rexagod** [comment]
It makes sense to acknowledge the resolution on https://github.com/kubernetes-sigs/kubebuilder/issues/3402 and not make them dependent on the "broken" pluralization logic upstream. Both of these places have procedures, albeit differing in nature, which if modified will have far-reaching repercussions.

Practically, any repository should follow the conventions set by its upstream to persist similar expectations across the ecosystem, however, if that should still be the case if the "conventions" (pluralization logic in `k/k`) are less than ideal is a grey area in itself.

IMHO we probably should stick to `flect`, since `apimachinery` acknowledges the procedure is broken, and implicitly, as I'm assuming, discourages depending on it.

**Comment by dgrisonnet** [comment]
@mrueg @rexagod did we reached a consensus here?

/remove-lifecycle stale
/triage accepted

**Comment by rexagod** [comment]
I believe if https://github.com/kubernetes/kube-state-metrics/issues/2093#issuecomment-2168574937 makes sense, then nothing needs to be done here, as we already use `flect`.

I do want to point out that this is one of the many things the CRDMetrics controller improves upon: https://github.com/rexagod/crdmetrics/blob/main/manifests/custom-resource.yaml#L27.

**Comment by rexagod** [comment]
Closing, feel free to reopen.
