### ISSUE TITLE
What kinds of pods are tracked by kube_pod_status_ready metric?

### ISSUE THREAD

**Issue by diane-dan** [kubernetes/kube-state-metrics#2185]
Could I know what kinds of pods are tracked in kube_pod_status_ready metric? Does it contains all control plane components' pod? In my experiment, I can see kube-proxy pod and kube-dns pod and of course the custom pods I deployed. However, I am not able to see kubelet pod or kube-apiserver pod. I could not find any documentation specifying it.

**Comment by dgrisonnet** [comment]
Kubelet is not a pod, it is a node-agent so it is normal that you can't see it in any kube_pod metrics.

However you should be able to see all the other pods including the kube-apiserver one. Can you perhaps see it with kubectl?

**Comment by diane-dan** [comment]
Could I know what do you mean by kubectl?

**Comment by dgrisonnet** [comment]
Can you see the pods in your cluster by using the `kubectl top pods` command?

https://kubernetes.io/docs/reference/kubectl/

**Comment by diane-dan** [comment]
I am able to see custom pods in my cluster, but not apiserver pods. Could I be I am use AKS([Azure Kubernetes Service)?

**Comment by dgrisonnet** [comment]
It could be, I don't know how they provision their clusters. I would suspect that kube-apiserver is running as a static pod managed by kubelet and that they didn't give the permission to kubelet to create the actual pod.

Since this is purely a specificity from a cloud provider and not an actual bug, I'll close the issue. If you still want to be able to see information about the kube-apiserver pods, I would encourage you to reach out to your cloud provider.

**Comment by diane-dan** [comment]
Got it, thank you so much!
