### ISSUE TITLE
Info and StateSet types cause errors when scrapped by Prometheus

### ISSUE THREAD

**Issue by defenestration** [kubernetes/kube-state-metrics#2248]
**What happened**:
When kube-state-metrics is configured with custom resources that produce Info and/or StateSet type of metrics, and Prometheus is configured with `--enable-feature=native-histograms`, prometheus is unable to scrape the kube-state-metrics target.

Filed an issue with prometheus here https://github.com/prometheus/prometheus/issues/13172 but seems like a possible issue with KSM as well.

**What you expected to happen**:

Successful scraping of metrics. 

**How to reproduce it (as minimally and precisely as possible)**:

Run prometheus with `--enable-feature=native-histograms` and setup kube-state-metrics with a metric of type: Info or Stateset. 

See a https://github.com/fluxcd/flux2-monitoring-example/issues/14 or https://github.com/defenestration/flux2-monitoring-example/pull/1 for an example setup.

**Anything else we need to know?**:

With the `native-histograms` feature disabled, prometheus seems to be able to scrape successfully. So a bug is also filed with prometheus. 

I guess the suggestion would be to include a setting on the custom resource to produce a promehteus-compatible type on the /metrics page for these custom resource types. 

**Environment**:

* kube-state-metrics version: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.1
* Kubernetes version (use `kubectl version`):  v1.27.7+k3s2
* Cloud provider or hardware configuration:  kind
* Other info:

**Comment by dgrisonnet** [comment]
The problem seem to be that when Prometheus has `--native-histograms` enabled, it tries to negociate for protobuf first and we manually force the text format instead since proto isn't supported: https://github.com/kubernetes/kube-state-metrics/blob/240cffd908220854a27f7e92d8157eaee4dc8d42/pkg/metricshandler/metrics_handler.go#L191-L194.

However, there doesn't seem to be any mechanism in custom-state-metrics to revert back to Prometheus types, so we continue to expose OpenMetrics types whilst the content-type is text.

I think we should rework https://github.com/kubernetes/kube-state-metrics/pull/1930 to enable the OpenMetrics types only when the OpenMetrics format is negociated.

**Comment by mrueg** [comment]
Yes we can definitely improve the negotiation part and contributions that do that are welcome.
My current suggestion for to workaround this is not to use Info or StateSet types in your custom config for CRS.

**Comment by rexagod** [comment]
IIUC All unrecognized types are categorized as [`COUNTER`s](https://github.com/prometheus/client_model/blob/master/go/metrics.pb.go#L975-L980), which are validated later on when consuming them in `common`, [which is where this error pops up from](https://github.com/prometheus/common/blob/658f673b7580e72a7d0c0fac26a67858b782fbd5/expfmt/text_parse.go#L525). As discussed with Damien in a call earlier, the best way forward to bypass the absence of certain `OpenMetrics` types in Prometheus, would be to detect if a `Proto` negotiation is in effect, and try to [specify a text-based format](https://github.com/prometheus/prometheus/pull/12738), since owing to the sheer amount of metrics that KSM generates, encoding these into metrics objects to facilitate things for KSM's own protobuf client would increase compute in a way that demands rigorous benchmarking beforehand.

**Comment by rexagod** [comment]
Ah, `scrape_protocols` is a client-side API, I imagine this renders it irrelevant for the use-case here, although, we can still manually set headers from [the supported list of text-based formats](https://github.com/prometheus/prometheus/pull/12738/files#diff-17f1012e0c2fbd9bcd8dff3c23b18ff4b6676eef3beca6f8a3e72e6a36633334R65-R66). I'll send a patch.
