### ISSUE TITLE
Feature request:  Add more labels to kube_pod_container_status_running

### ISSUE THREAD

**Issue by somejfn** [kubernetes/kube-state-metrics#27]
Thanks to this project I can create Prom alerts on the hosted deployment state.  Big +1 in filling this gap.

Now Im attempting to create an alert based on a deployment's "dispersion" ratio.... that is,  should the Kube scheduler had little choice in picking nodes with resources (i.e. node outage),  that a given deployment's replicas are running on the same or too few Kubernetes node.   

I think kube_pod_container_status_running would be the right place... but I'd need to have the deployment name and the node the pod is running on as labels. Then a Prom query would compute a ratio on POD running / unique nodes.  Does that make sense ?

**Comment by brancz** [comment]
I am unsure if we are able to get these upward and cross linking references from a pod. I'll take a little time to investigate.

**Comment by fabxc** [comment]
You generally want to keep the number of 1:1 labels to a minimum. Otherwise, over time, you would basically enrich every metrics with all transitive and static label dimensions. If then something changes unexpectedly after all, you break all time series, as their identity is given by the full combination of all labels.
Generally speaking, you want your metrics to normalized.

What we probably want here are metrics that express the relation from pod to deployment and pod to node. In your queries, you can then connect the time series along them.

So the node name could probably be attached to the `kube_pod_info` metric as a label: https://github.com/kubernetes/kube-state-metrics/blob/master/pod.go#L26-L30

We could have a metric on the `created-by` relation (currently living as a `SerializedRef` type in the `kubernetes.io/created-by` annotation. For example (`creator_namespace` would be redundant):

`kube_pod_created_by{pod="my-app-aef242",namespace="prod",creator_kind="ReplicaSet", creator_name="my-app-12341"}    1` 

Unfortunately, relation from ReplicaSet to Deployment is not yet accessible in a similar way, but we can just use regex matching below to express it via ReplicaSets.

Your PromQL query could then look like:

```
count(
  count by(node_name) (
     kube_pod_info 
     and on(pod) kube_pod_status_phase{phase="Running"}
     and on(pod) kube_pod_created_by{creator_kind="ReplicaSet", creator_name=~"my-app-[0-9]+"})
  )
)
/ count(kube_node_info)
```

I know this is not a trivial but imagine that this is just one use case of many to incorporate relationships between components into your queries. So hard cording it into the exposed metrics does solve just a single use case of many.

[Recording rules](https://prometheus.io/docs/querying/rules/#recording-rules) can help you here to break these parts out into separate metrics, which can be useful for other alerts and dashboards as well.

I think a pull request for metric additions/changes as described above would be welcome.
