### ISSUE TITLE
Expose metrics about kube-state-metrics itself

### ISSUE THREAD

**Issue by brancz** [kubernetes/kube-state-metrics#296]
kube-state-metrics currently only exposes metrics about the Kubernetes objects, but kube-state-metrics itself should also be "monitorable". For this purpose I would suggest an additional metrics endpoint (maybe `/metrics/kube-state-metrics`, there we can expose metrics like the number of objects used to generate metrics and go runtime as well as process statistics.

@andyxning

**Comment by andrewhowdencom** [comment]
I might suggest keeping them at the same endpoint, but modifying the names. I think I remember Brian Brazil saying at one point rather than instrument applications, the goal is to instrument libraries. The library name then becomes the metric prefix (kube_state_metrics_kube_up 1 or smth), and the application included through discovery as a label, or relabelled. 

Go metrics are already exported in this way for the node and varnish exporter (from my stack; go_gc_duration_seconds_count{instance="__ADDRESS_OF_EXPORTER__",job="node",project="__RELABELLED_CODE__"})

Alternatively, the more common convention for splitting metrics seems to be doing so via port: https://github.com/prometheus/prometheus/issues/2523

**Comment by brancz** [comment]
Right, the reason why for this specific exporter it would make sense to have separate endpoints (whether on a different or the same HTTP server), is because for the current `/metrics` endpoint, one will want to use the `honor_labels` configuration option, whereas this is not desirable for metrics by kube-state-metrics itself.

I'm happy to use a different port rather than a path, that way there is less configuration overhead.

**Comment by andyxning** [comment]
@brancz Agreed with using another different port for kube-state-metrics self metrics. Another command option `--ksm-port` should be added to kube-state-metrics and this should be added to readme.

**Comment by brancz** [comment]
Sounds good to me.

**Comment by andyxning** [comment]
After a rethink about the go runtime metrics of kube-state-metrics, it has been available under `port/metrics`. It seems difficult to split the go runtime metrics to another metrics endpoint.

**Comment by andyxning** [comment]
BTW, we need to record the count of scraped resource objects, only when `port/metrics` is scraped we can count the number of scraped resource objects. I.e., they need to be calculated at the same time.

So, it should be and must be displayed under the same endpoint.
