### ISSUE TITLE
use dumb-init as entry-point ?

### ISSUE THREAD

**Issue by grosser** [kubernetes/kube-state-metrics#347]
I can make a PR if you want it, we are trying to use it for all images we deploy.

https://github.com/Yelp/dumb-init

**Comment by brancz** [comment]
kube-state-metrics is a single process so dumb-init is not really necessary in my opinion. Do you have a concrete problem?

**Comment by grosser** [comment]
No concrete problem, feel free to close.
I would like to know if for some reason single-binary go apps like this are
exempt from the problems dumb-init describes, since then we could stop
doing it for ours :)

On Wed, Jan 17, 2018 at 2:35 AM, Frederic Branczyk <notifications@github.com

**Comment by andyxning** [comment]
@grosser IMO, the most important thing for PID 1 is to pass through received signals and reclaim the finished children process. For single go binary which does no spawn sub processes, there are no requirements to reclaim finished sub processes. As for signals, since it has no sub processes, there is not need to pass received signals either. What go binary apps, i.e., kube-state-metrics, does is receive the signal and shutdown itself properly.

Close this since it seems there is no need to add some init system to supervisor kube-state-metrics. Feel free to reopen it if you still have some questions. :)
