### ISSUE TITLE
kube_state_matrics is not showing valid result

### ISSUE THREAD

**Issue by maloochpich** [kubernetes/kube-state-metrics#360]
When I try to use any kube graphs for prometheus is showing invalid result.

Example:
when I run kube_pod_container_status_waiting_reason:

`kube_pod_container_status_waiting_reason{app="kube-state-metrics",container="blackbox-exporter",job="kubernetes-endpoints",kubernetes_name="kube-state-metrics",kubernetes_namespace="monitoring",namespace="monitoring",pod="blackbox-exporter-85cdb97d8f-6fjn2",reason="ErrImagePull"}`

$kubectl get pods -n monitoring
  blackbox-exporter-85cdb97d8f-6fjn2    1/1       Running   0          2h

**Comment by maloochpich** [comment]
@andyxning Yes my question is if at some point it was failing and kube-state-metrics catch that why is not updating it and getting away from my Prometheus alert.

**Comment by andyxning** [comment]
Sorry for the late. @maloochpich 
> my question is if at some point it was failing and kube-state-metrics catch that why is not updating it and getting away from my Prometheus alert.

What kube-state-metrics do is to update the value for `kube_pod_container_status_waiting_reason{reason="ErrImagePull"}` to zero instead of one after the `ErrImagePull` is recovered. kube-state-metrics will not ignore any metrics instead it will output the same metrics with value setted to zero to indicate that some condition is no happening.
