### ISSUE TITLE
Get metrics of pods status per namespace

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kube-state-metrics#4]
Hello,

It would be really useful to get metric of status pods per namespaces like: Running, CrashLoopBackoff, Pending, etc ...

Thanks !

**Comment by brancz** [comment]
It probably makes sense to tackle #7 or update the currently vendored k8s client before adding more states as we're missing a lot of state constants, which I would like to avoid duplication for. But with the recent PRs we're already exposing Pending/Running/Succeeded/Failed/Unknown state. (see [here](https://github.com/kubernetes/kube-state-metrics#pod-metrics))

**Comment by brancz** [comment]
As #7 is fixed, do you think it would make sense to add another label `reason` to the container status `kube_pod_container_status_waiting `/`kube_pod_container_status_terminated` metrics? That way we there would be more insight into why the container is in that state. The only problem I see is that that might generate a lot of time series in Prometheus as I don't know how many "Reasons" there are... do you have any comments on this @fabxc ?

**Comment by fabxc** [comment]
Yes, I think the last point is a blocker for this. Think of thousands of pods, then we have several time series for the status as it is. First, we had to know every possible reason and then have each of it set for every possible status. Given that we are talking about thousands of pods as is, the cost-benefit-ratio is diminishing.
The reason seems rather interesting when you already reached the stage of debugging this directly after looking at metrics.

**Comment by brancz** [comment]
Agreed. Closing as the states described in my above comment are already exposed.
