### ISSUE TITLE
Add current resource usage for per container of pod?

### ISSUE THREAD

**Issue by penglongli** [kubernetes/kube-state-metrics#497]
### Description
In a kubernetes cluster, there probably have multiple projects(namespace). 

The cAdvisor can provide the metrics of running containers on every node. **But it will provides all projects' containers' metrics.** I don't want it.

### What i want
I only want get containers' request resource、limit resource、current usage resource from a single namespace.

And kube-state-metrics's metrics don't show the current resource usage.  Can you add the current usage to it?

**Comment by brancz** [comment]
I understand your need for this, however, kube-state-metrics is only about converting Kubernetes objects to Prometheus metrics. I believe what you are requesting is something that should exist, but not in kube-state-metrics. We should build as a proxy in front of cAdvisor, or a central Prometheus server that can be federated from, in order to perform authentication/authorization for that individual namespace. Security and performance wise the second option is likely the best, as having users have access to cAdvisor or even discover nodes is likely not something we want (I'm thinking in terms of a multi-tenant system, which is what your environment sounds like is going towards). In fact I actually have some PoCs in the works, but nothing that I can show just yet regarding this, but we're working on it :slightly_smiling_face:, just not in kube-state-metrics.

**Comment by gwperry** [comment]
I am looking for the same solution.  Is there any idea when a solution will be available?

**Comment by brancz** [comment]
We are currently working towards publishing some solutions for this, it shouldn’t be more than a month or two before it’s available.

**Comment by weeco** [comment]
@brancz Any updates?

**Comment by brancz** [comment]
We've published the label enforcer: https://github.com/openshift/prom-label-proxy

In combination with the [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) this can build a story where individual Prometheus servers can federate the metrics for its set of namespaces. We are likely going to integrate this into the kube-prometheus stack, where it will soon be available out of the box: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus
