### ISSUE TITLE
kube_service_info matrics should show external-ip assign to service

### ISSUE THREAD

**Issue by Deepak1100** [kubernetes/kube-state-metrics#544]
> Uncomment only one, leave it on its own line: 

> /kind feature

**What happened**:
i am trying to get somehow get external-ip attribute of service in prometheus so i can map it with cloudwatch exporter matrics for that elb. but i didn't find any matrics giving me this information.(whic have service and its elb attached)

```
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP                                                              PORT(S)        AGE
app-external   LoadBalancer   172.20.19.131    asdfasdfa-asdfasd-asdfasf.us-east-1.elb.amazonaws.com   443:31255/TCP                                                                      4d
```
**What you expected to happen**:
If there is any matrics which can give me all service info like external-ip then i can use it on multiple places
**How to reproduce it (as minimally and precisely as possible)**:
just add annotation while creating service which will cretate elb and add it as its externap-ip attribute
```
service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```
and check kube_service_info or kube_service_label any other metrics and there is no way to find external-ip of service.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Kube-state-metrics image version
```
gcr.io/google_containers/kube-state-metrics:v1.2.0
```

**Comment by mxinden** [comment]
@Deepak1100 you might be able to [join the metric](https://github.com/kubernetes/kube-state-metrics/tree/master/Documentation#join-metrics) by its `cluster_ip` with metrics of the ELB?

**Comment by Patstrom** [comment]
I am currently implementing this (https://github.com/AbiosGaming/kube-state-metrics/commit/af9787195b869c2b84ae92f09fdab06bfd8bbcad) and wondering what would be the best way to handle the prometheus names.

Currently I have added `external_name` and `loadbalancer_ip` (taken from `v1.Service.Spec`) to `kube_service_info`. `v1.Service.Spec` also defines `ExternalIPs` as an array so I've added the `kube_service_spec_external_ip` fqName where a service will appear once for every `external_ip` (or once with an empty `external_ip` if the array is empty).

I've also added the `kube_service_status_load_balancer_ingress` with the labels `ip` and `hostname`, mimicking the `v1.Service.Status.LoadBalancer.Ingress` array. Similarly to `external_ip`, each service will appear once for every `LoadBalancerIngress`, or just once with empty labels.

It might be a little excessive to always include `external_name` and `loadbalancer_ip` with `kube_service_info`, and they could be split up to their own series. However, since some "non-generic resource metrics" are being deprecated adding more might not be the best option.

Any thoughts?
