### ISSUE TITLE
Question: adding ingress metrics?

### ISSUE THREAD

**Issue by ebabani** [kubernetes/kube-state-metrics#573]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Hi. Wanted to check what the maintainers think about exposing ingress metrics. 

I saw that there was a PR (https://github.com/kubernetes/kube-state-metrics/pull/225) that was closed. 

In our case, the use case is to alert on possible duplicate ingress paths created for the same host (undefined behaviour on our system).

I can think of a number of other use cases, like alerting of exposed test paths on prod.

Let me know what you think, and if it's worth it to re-open that PR, or make a new one adding ingress metrics. 

Thanks

**Comment by brancz** [comment]
I think they're worth adding, but given the amount of large scale changes we have already queued up, I don't think I would feel comfortable merging that right now, but feel free to prepare a pull request to do so :slightly_smiling_face: . (note that the changes done in the closed PR are not possible in exactly that way anymore, as the kube-state-metrics architecture heavily changes since then)
