### ISSUE TITLE
Feature Request: Include Deployment and Pod Annotations

### ISSUE THREAD

**Issue by bluechips23** [kubernetes/kube-state-metrics#574]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**: Deployment and Pod Annotations are not included today in kube_state_metrics

**What you expected to happen**: Include Deployment and Pod Annotations

**Anything else we need to know?**: 
Deployment and Pod annotations contain some additional metadata information which are important. These metadata could be included when generating alerts using Prometheus. For instance, if the annotation has contact information (email addresses, etc), then Prometheus can fetch those to send alerts. Labels have a 63 character limit and do not support characters such as "@", "," or ";", making them unsuitable to include any email addresses. Annotations seem like an ideal place to store these information.

Please consider to see if deployment and pod annotations can be included.

**Comment by jacobstr** [comment]
These could be useful in conjunction with approaches such as this one: https://karlstoney.com/2018/07/07/managing-your-costs-on-kubernetes/

The data exposed by `kube-state-metrics` is used to generate cost estimates for pods. Pushing a subset of labels/annotations into the metric dimensions would allow cost breakdown on a logical application level.

**Comment by brancz** [comment]
@jacobstr at this point I need to make sure you understand that Prometheus is imprecise by design. I cannot recommend you to do billing on the data, if you need any form of precision :slightly_smiling_face: .

Having annotations of pods as labels has been requested before and is in some form theoretically possible but must be disabled by default as it will cause a huge amount of data in most clusters for Prometheus, that I'm not comfortable enabling by default.

**Comment by bluechips23** [comment]
@brancz Having it as an optional feature is fine with it being disabled by default. We just want to leverage the ability to capture some metadata in addition to the metrics we are collecting. Labels can only do so much, whereas annotations are versatile. For some teams having annotations with a side effect of additional data may not be worth it, but for our objective, it could be worth it. At the least we want to have an option to evaluate and understand the pros and cons.

**Comment by jacobstr** [comment]
@brancz yes - understood re: accuracy. Our use case is largely for internal dashboards to provide some reasonable ballparks for internal development teams. Today, folks are fairly abstracted from the cost of `2500m cpu * 16 replicas`. It's not meant for billing, but to provide some visibility into costs. Apologies to the op - I don't want mean to hijack since his use case is quite different but it might make this story more compelling with some divergent examples benefiting from this functionality.

Using all annotations / labels could very well cause a cardinality explosion in emitted metrics. A possible approach could be an opt-in configuration requiring the whitelisting of specific labels or annotations.

**Comment by lonestriker** [comment]
Our use of Kubernetes would greatly benefit from having the pod and deployment annotations exposed.  I'd like to add my vote for this feature to be added as an opt-in configuration option.

/reopen
