### ISSUE TITLE
[feature] Add metrics for v1.ComponentStatusList

### ISSUE THREAD

**Issue by Crapworks** [kubernetes/kube-state-metrics#58]
Hi all!

I just stumbled across this project and was doing what you are doing in a much more sloppy way via python. I would like to switch over to kube-state-metric but there is one thing missing: Getting the component statuses. They can be retrieved via [API](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_componentstatuslist). I was trying to do it myself and create a PR but I have never worked with GO before, so I am afraid I am not much of a help here.

This endpoint basicaly shows the internal monitoring information about the kube-controller-manager, the sheduler and the etcd servers attached. I am mainly using it to create alerts via [Kapacitor](https://github.com/influxdata/kapacitor). Would that be something you could implement?

Cheers,
Christian

**Comment by brancz** [comment]
`kube-state-metrics` is intends to simply convert objects that can be retrieved via the API to be represented in the Prometheus exposition format. While getting the component statuses might be something we could add, we won't integrate with other tools to create alerting. The way to alert on information collected through `kube-state-metrics` is by having a Prometheus collect these metrics, and have alerting rules within Prometheus that will fire on appropriate conditions.

**Comment by brancz** [comment]
However, I don't think getting the component statuses is a particularly good idea as there are many indirections of those health statuses. It is always best to get metrics and health information directly from its source. With Prometheus you would have Prometheus scrape the Kubernetes components. This is called whitebox monitoring, because Prometheus knows about the topology of your cluster, by discovering everything through the Kubernetes API. We have assembled a collection of resources to get started monitoring your Kubernetes cluster with Prometheus at [coreos/kube-prometheus](https://github.com/coreos/kube-prometheus).
