### ISSUE TITLE
How kube-metrics will be fetched by Prometheus if it is available on a different node

### ISSUE THREAD

**Issue by vivekj11** [kubernetes/kube-state-metrics#665]
**What happened**:
I have a k8s cluster on which I deployed Kube-state-metrics and Prometheus. Things worked fine, Prometheus was able to fetch all metrics.
Now I want to keep Prometheus on a different server(not a part of the cluster). when I checked Kube-state-metrics, they are not available externally. 
So how can I forward all metrics from my k8s cluster node using Kube-state-metrics to my Prometheus 
which is hosted on a different node.

I am looking for some endpoint which I can put in my prometheus.yml file so it can start scraping metrics from this cluster node.

**Comment by mxinden** [comment]
You would use ingress to expose kube-state-metrics to the outside so that Prometheus can access it. You can find more details here: https://kubernetes.io/docs/concepts/services-networking/ingress/

I am closing this issue as this is not related to kube-state-metrics. Let us know if the above was of any help.
